const schema = `
CREATE TABLE IF NOT EXISTS Users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Workouts (
  WorkoutID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  WorkoutName VARCHAR(255) NOT NULL,
  Duration INT NOT NULL,
  CaloriesBurned FLOAT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Meals (
  MealID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  MealName VARCHAR(255) NOT NULL,
  Calories FLOAT NOT NULL,
  Date DATE NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);
`;

module.exports = schema;
